### ISSUE TITLE
Bot Token

### ISSUE THREAD

**Issue by R4z0r1989** [crycode-de/ioBroker.discord#13]
Hello,

just want to report, i think its, a bug.
The First Part of my Token that Discord gave me ist 2 Characters to long,
so i cannot put my Token into the instance of Discord.

Sry for my bad English.

**Comment by crycode-de** [comment]
Hi, thank you for the report.
This is already fixed since release v1.1.5.
Currently v1.1.6 is available via NPM or GitHub.

**Comment by R4z0r1989** [comment]
Did it. Thx :-).
