### ISSUE TITLE
Please correct npm maintainers configuration.

### ISSUE THREAD

**Issue by GermanBluefox** [crycode-de/ioBroker.discord#44]
## ioBroker adapter checker for npm access

Access right check for adapter discord returned the following issue:

Bluefox was not found in the collaborators on NPM!.
Please execute in adapter directory: "npm owner add bluefox iobroker.discord"

Current maintainers are 
    crycode <peter@crycode.de>

Please fix the above error as soon as possible.
All adapters listed at ioBroker repositories must have 'bluefox' added as maintainer.

Future version updates at the repositories will be suspended until this problem is fixed.

**Comment by crycode-de** [comment]
Done
