### ISSUE TITLE
Blockly Probleme ...

### ISSUE THREAD

**Issue by sonny1985** [crycode-de/ioBroker.discord#63]
Hallo. Bitte Hilfe :)

Darf ich das da gleich "herverlinken"
Ich kenn mich da sonst leider nicht sorecht aus.
Hab das Problem in den JS Adapter geschrieben, wusste nicht das es direkt mit dem Discord Adapter zusammenhängt.

https://github.com/ioBroker/ioBroker.javascript/issues/1620

LG und danke.

**Comment by crycode-de** [comment]
Hallo, danke fürs Melden des Problems!
Schau ich mir an uns versuche das zeitnah zu lösen. :)

**Comment by sonny1985** [comment]
Vielen dank :) Natürlich gerne. 
Auch möchte ich für den tollen Adapter ein großes Danke und ein dickes Lob aussprechen.

**Comment by crycode-de** [comment]
Danke! 🙂

**Comment by crycode-de** [comment]
@sonny1985 Problem sollte jetzt behoben sein. Kannst du bitte mal die Version von GitHub installieren und testen? 🙂

**Comment by sonny1985** [comment]
Wow das ging ja schnell... Aber natürlich gerne :), Bisschen Geduld-  Ich geb gleich Bescheid ...

**Comment by sonny1985** [comment]
Wow, danke dir vielmals für das schnelle fixen. Das sieht nun ganz toll aus :)
Ich bau morgen gleich 3 Scripte damit :) 
LG und schönes Wochenende .
Sollte mir etwas auffallen, meld ich mich natürlich !

![Screenshot 2024-06-29 212248](https://github.com/crycode-de/ioBroker.discord/assets/133059571/c7051ea2-7f3b-40cd-b5c3-1bf35a367068)

**Comment by crycode-de** [comment]
Super, danke dir fürs schnelle Testen. 👍
Dann mach ich gleich mal noch den Release fürs latest Repo.
Ebenfalls schönes Wochenende!
